name: Build and Deploy Node.js App to Azure Web App
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify app.js exists
        run: |
          if [ ! -f app.js ]; then
            echo "Error: app.js not found"
            exit 1
          fi
          ls -l app.js
      - name: Run Semgrep Scan
        run: |
          # Scans only app.js, excludes node_modules via .semgrepignore
          semgrep ci --include app.js --json --output=semgrep-results.json
          cat semgrep-results.json
          # Fails workflow if any findings are detected, ensuring red X
          jq -e '.results | length > 0' semgrep-results.json && { echo "Vulnerabilities found, failing workflow"; exit 1; }
      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json

  build:
    name: build
    needs: semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    name: deploy
    needs: [semgrep, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C34E57C1C224509ABA03A55CEBFE2F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E908A152458348C3B2528C8B384DC577 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_868CDA1925B9444091C67DED9736EEFE }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'secure-node-app-123'
          slot-name: 'Production'
          package: .