name: Semgrep SAST and SCA Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep SAST
        run: semgrep --config=auto --severity ERROR --json > semgrep-sast-results.json
      - name: Run Semgrep SCA
        run: semgrep --config=p/supply-chain --json > semgrep-sca-results.json
      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: |
            semgrep-sast-results.json
            semgrep-sca-results.json