name: Semgrep and Trivy Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep SAST
        run: semgrep --config=auto --severity ERROR --json > semgrep-sast-results.json
      - name: Run Semgrep SCA
        run: semgrep --config=p/supply-chain --json > semgrep-sca-results.json
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t my-node-app:latest .
      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-node-app:latest
          format: json
          output: trivy-results.json
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            semgrep-sast-results.json
            semgrep-sca-results.json
            trivy-results.json